name: Self-Hosted CI with Local Docker & Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Ensure Docker is available
      - name: Docker version
        run: docker --version

      # Step 3: Build local Docker image
      - name: Build Docker image
        run: docker build -t wisecow:local .

      # Step 4: Load image into local K8s cluster (minikube/self-hosted)
      - name: Load Docker image into cluster
        run: |
          # If using minikube
          # minikube image load wisecow:local

          # If using Docker Desktop / self-hosted cluster
          kubectl delete pod -l app=wisecow --ignore-not-found
          # Ensure your cluster nodes can access local images

      # Step 5: Apply Kubernetes manifests
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f wisecow-deployment.yaml
          kubectl apply -f wisecow-service.yaml
          kubectl apply -f wisecow-ingress.yaml

      # Step 6: Wait for pods to be ready
      - name: Wait for deployment rollout
        run: |
          kubectl rollout status deployment/wisecow --timeout=120s
          kubectl get pods
          kubectl get svc
          kubectl get ingress
