name: Self-Hosted CI with Local Docker Image...

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker (self-hosted runner must have Docker installed)
      - name: Set up Docker
        run: docker --version

      # Step 3: Build local Docker image
      - name: Build Docker image
        run: |
          docker build -t wisecow:local .

      # Step 4: Optional - run container from local image for tests
      - name: Run container for testing
        run: |
          docker run --rm -d --name wisecow-test -p 4499:4499 wisecow:local
          # Wait for container to be ready (replace with actual health check if needed)
          sleep 10
          curl -v http://localhost:4499/health || true
          docker stop wisecow-test

      # Step 5: Backend/Frontend builds if needed
      - name: Build backend artifact
        run: ./mvnw clean package -DskipTests

      - name: Build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      # Step 6: Optional deployment step using local image
      # - name: Deploy
      #   run: docker run -d -p 4499:4499 wisecow:local
