name: CI/CD for Wisecow...

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted   # Your MacBook runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0

      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Verify Kubernetes connection
        run: kubectl get nodes

      - name: Apply Wisecow deployment (first-time or update)
        run: |
          kubectl apply -f wisecow-deployment.yaml

      - name: Update image to latest
        run: |
          kubectl set image deployment/wisecow-deployment wisecow=ghcr.io/atind13/wisecow:latest
          kubectl rollout status deployment/wisecow-deployment
