name: CI/CD for Wisecow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: self-hosted   # your Mac runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/wisecow:latest .
          docker push ghcr.io/${{ github.repository_owner }}/wisecow:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted   # run deploy on your Mac too
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Kubernetes connection
        run: kubectl get nodes   # confirm connection

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/wisecow-deployment wisecow=ghcr.io/${{ github.repository_owner }}/wisecow:latest
          kubectl rollout status deployment/wisecow-deployment
